stages:
  - build
#  - test

backend-build:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - npm run build

frontend-build:
  image: node:latest
  script:
    - yarn
