stages:
  - build
  - test


backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
  script:
    - npm install
    - npm run build

frontend-build:
  image: node:latest
  stage: build
  script:
    - yarn


image: docker:latest

backend-test:
  image: docker/compose:latest
  stage: test
  before_script:
    - cd backend
  script:
    - docker-compose run --entrypoint "npm run unittest" backend

frontend-test:
  image: docker/compose:latest
  stage: test
  script:
    - docker-compose run --entrypoint "npm run test" frontend
