stages:
  - build
  - test


backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
  script:
    - npm install
    - npm run build

frontend-build:
  image: node:latest
  stage: build
  script:
    - yarn


image: docker:latest
services:
  - docker:dind

backend-test:
  image: docker/compose:latest
  stage: test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd backend
  script:
    - docker-compose run --entrypoint "npm run unittest" backend

frontend-test:
  image: docker/compose:latest
  stage: test
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose run --entrypoint "npm run test" frontend
